/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: patrakeevasveta (https://sketchfab.com/patrakeevasveta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/refrigerator-38a739d5361547b7b8b7d87ab73c9fa3
title: Refrigerator
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fridge.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[2.02, 0.04, 13.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.13, -0.12, 1.01]}>
              <mesh geometry={nodes.box_refrigerator004_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[-0.13, -0.12, 1.01]}>
              <mesh geometry={nodes.box_refrigerator003_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0, -0.17, 0.25]}>
              <mesh geometry={nodes.box_refrigerator_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0, -0.17, 0.46]}>
              <mesh geometry={nodes.box_refrigerator002_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0, -0.18, 0.66]}>
              <mesh geometry={nodes.box_refrigerator001_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0.29, -0.34, 1.3]} rotation={[0, 0, 1.9]}>
              <group position={[-0.54, -0.08, -0.27]}>
                <mesh geometry={nodes.handle_refrigerator003_refrigerator_0.geometry} material={materials.refrigerator} />
              </group>
              <mesh geometry={nodes.door_refrigerator_refrigerator_0.geometry} material={materials.refrigerator} />
              <mesh geometry={nodes.door_refrigerator_glass_0.geometry} material={materials.glass} />
            </group>
            <group position={[0.29, -0.34, 0.4]} rotation={[0, 0, 1.9]}>
              <group position={[-0.54, -0.08, 0.17]}>
                <mesh geometry={nodes.handle_refrigerator002_refrigerator_0.geometry} material={materials.refrigerator} />
              </group>
              <mesh geometry={nodes.door_refrigerator001_refrigerator_0.geometry} material={materials.refrigerator} />
            </group>
            <mesh geometry={nodes.refrigerator_refrigerator_0.geometry} material={materials.refrigerator} />
            <mesh geometry={nodes.refrigerator_glass_0.geometry} material={materials.glass} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fridge.gltf')
